apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: devops-toolkit
  labels:
    app: devops-toolkit
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: devops-toolkit
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 15}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  template:
    metadata:
      labels:
        app: devops-toolkit
    spec:
      containers:
      - name: devops-toolkit
        image: sharief212/devops-toolkit:1.0.6
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 80m
            memory: 128Mi

